### ISSUE TITLE
Assertion check_rank fails on large files

### ISSUE THREAD

**Issue by maxrossi91** [nicolaprezza/rlbwt2lcp#1]
I tested the construction on BWTs with more than 2^32 characters in debug mode and the assertion check_rank fails.

The problem could be that in both dna_string.hpp and dna_string_n.hpp the main for has int index instead of size_t.

**Comment by nicolaprezza** [comment]
Hi Max! yes, that's probably the reason. Check if it works now.

**Comment by maxrossi91** [comment]
Hi, Nicola,

I checked and now it works. Thanks.

**Comment by nicolaprezza** [comment]
Thanks!

Il Lun 27 Lug 2020, 15:45 Massimiliano Rossi <notifications@github.com> ha
scritto:
